name: setup
description: 'Setup Node.js with .node-version file and cache npm dependencies using cache v4'

runs:
  using: "composite"
  steps:

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        registry-url: 'https://npm.pkg.github.com'
        scope: '@omni-stove'

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - name: Restore npm cache
      uses: actions/cache/restore@v4
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Save npm cache
      uses: actions/cache/save@v4
      if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
