name: setup
description: 'Setup Node.js with .node-version file and cache npm dependencies using cache v4'

runs:
  using: "composite"
  steps:

    - name: Generate app token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: 1625136
        private-key: ${{ env.PRIVATE_KEY }}
        owner: omni-stove

    - name: Debug - Check token permissions
      shell: bash
      run: |
        echo "Testing GitHub App token..."
        curl -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/user
        echo ""
        echo "Checking package access..."
        curl -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/orgs/omni-stove/packages

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        registry-url: 'https://npm.pkg.github.com'
        scope: '@omni-stove'

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - name: Restore npm cache
      uses: actions/cache/restore@v4
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ steps.app-token.outputs.token }}
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Save npm cache
      uses: actions/cache/save@v4
      if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
